# Generated by Django 3.1.3 on 2020-11-18 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20201112_0447'),
        ('authentication', '0002_delete_userprofile'),
        ('authentication', '0002_delete_contact'),
    ]

    operations = [
    ]
